### ISSUE TITLE
Direwolf20 1.16 FTB modpack crashed when i tried to open pocketstorage

### ISSUE THREAD

**Issue by draav** [Flanks255/pocketstorage#10]
Not sure what i did wrong, i had just thrown something on the ground from a chest, went to go pick it up, then tried to open pocket storage, and my game crashed.

The screen was frozen on the pocketstorage inventory, but instead of seeing all my items, every slot was empty.

Here is a pastebin of the log.
https://paste.ee/p/8Yh52

Let me know if there is any info you need that isn't present in the logs

**Comment by Flanks255** [comment]
Looks to be a fluke to me, like, a mismatch between the threads, hopefully it doesn't happen again.
