### ISSUE TITLE
Feature request: Inventory Transfer

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [Flanks255/pocketstorage#11]
Whenever I want to move all the things out of the pocket is too slow, I hope to add a machine can put the pocket into it, and then automatically want to specify the items extracted

**Comment by Flanks255** [comment]
This actually exists in a way... kind of, you can crouch + right click an inventory with the pocket storage, and it will push out whatever items it can into the inventory(leaving 1 in each slot behind), and if you crouch + left click, you will absorb all the items that it can from the inventory into the pocket storage.

**Comment by ShoukakuChuuCC** [comment]
So there is such a design, I see, thank you!

**Comment by Flanks255** [comment]
Ya, its something ive forgotten to really document anywhere.
