### ISSUE TITLE
Feature request: empty into chests

### ISSUE THREAD

**Issue by RedMoikle** [Flanks255/pocketstorage#12]
It is annoying to have to click an item type over and over to transfer items between pocket and chest. 

you have to repeatedly click to move it into your main inventory, then open the chest, shift+double click to transfer it all to the chest, then repeat until you empty the pocket.

It would be nice to have an "empty to nearby chest" option

**Comment by Flanks255** [comment]
This exists already kind of 
![image](https://user-images.githubusercontent.com/32142731/104656446-edc95a80-5684-11eb-9a28-6191bdc0c951.png)
