### ISSUE TITLE
PSU voids items taken from inventory space

### ISSUE THREAD

**Issue by ArsiTheFox** [Flanks255/pocketstorage#20]
The Storage units should only void items being picked up from the ground and not an inventory space... or have a config that allows us to change it because I shift left clicked a drawer with almost 3M items in it and deleted it all except for 65K Tier 3 PSU.

When extracting from an inventory it should only grab the allowed amount and not all of it then void

**Comment by Flanks255** [comment]
Found the problem finally, it was never supposed to be voiding those items, but typos made it do otherwise lol, fixing soonish.
