### ISSUE TITLE
[1.20.1] Pocket Storage is not showing up in JEI.

### ISSUE THREAD

**Issue by Gbergz** [Flanks255/pocketstorage#23]
Title ^

Screenshot: 
![bild](https://github.com/Flanks255/pocketstorage/assets/26634554/deed10cb-befe-4762-8097-6ce3516936df)

MC: 1.20.1
Forge: 47.1.3
Pocket Storage: 1.0.2-build.26

**Comment by Flanks255** [comment]
Ya, apparently at some point JEI started relying on the creative mode tabs for what to display, and i wasnt adding them to any tab, incoming fix.
