### ISSUE TITLE
Bug? - Locked Pocked Storage slot

### ISSUE THREAD

**Issue by MacatMovie** [Flanks255/pocketstorage#24]
Hello.
I've been playing with a few friends on a custom-made modpack that has been evolving over time, with gaining and losing mods. And one friend noticed a problem with building gadgets, most likely related to a removed mod. He was storing blocks in the pocket storage, and now just noticed, that he has empty slots (presumably spots of removed blocks/changed block ID from other mods) that are locked, and can't have anything inserted in them.

Is there something I'm missing, or is this a bug/unfixable?

Thanks for any help!

**Comment by Flanks255** [comment]
Oh interesting, so items in the storage from a mod that was then later removed? that might cause an issue, ill look into it.

**Comment by Flanks255** [comment]
Sorry, forgot about this bug for... awhile... fixed in 1.21, ill try to push fixes out to older versions when i have the energy... b553e3a
