### ISSUE TITLE
KubeJS doesn't recognize custom Upgrade recipe type

### ISSUE THREAD

**Issue by Samrel556** [Flanks255/pocketstorage#25]
Trying to use KubeJS to change the recipe for Pocket Storage Units fails due to KubeJS not recognizing the custom pocketstorage:upgrade recipes type. 

```
ServerEvents.recipes(event => {
    event.custom({
	type: 'pocketstorage:upgrade',
	value:{
	    pattern: [
		'ICI',
		'PSP',
		'ICI'
	    ],
	    key:{
		I: {item: 'minecraft:gold_ingot'},
		C: {tag: 'forge:chest/wooden'},
		P: {item: 'minecraft:piston'},
		S: {item: 'pocketstorage:psu_1'}
	    },
	    result:{item: 'pocketstorage:psu_2'}
	}
    })

})
```

This script should rotate the recipe 90 degrees. However KubeJS throws an error stating "Unknown recipe type: pocketstorage:upgrade". This recipe type is pulled directly from the recipe json found in the Github.

Testing done with newest available versions of KubeJS(2001.6.5-build.7) and Pocket Storage(1.0.4-build.28) on minecraft version 1.20.1 with NeoForge 47.1.101

**Comment by Flanks255** [comment]
try "pocketstorage:data_upgrade", it changed in 1.20.4 when i rewrote all that.

**Comment by Samrel556** [comment]
Nope. It doesn't throw an error but no change to the recipe.

**Comment by Flanks255** [comment]
i have not done much kubejs stuff, but here is the normal recipe for reference, [https://github.com/Flanks255/pocketstorage/blob/1.20.1-forge/src/generated/resources/data/pocketstorage/recipes/tier2.json](https://github.com/Flanks255/pocketstorage/blob/1.20.1-forge/src/generated/resources/data/pocketstorage/recipes/tier2.json)

the older version has a specific ingredient type as well, while that shouldnt cause a kubejs error, it would make the recipe not function correctly.

**Comment by Samrel556** [comment]
That is the file I was referencing. That's also why I am so confused why its saying the recipe type doesn't exist. It clearly does inside the mod. Sophisticated Backpacks has a similar custom recipe type that extends ShapedCrafting and it works perfectly.

**Comment by Flanks255** [comment]
Right, but you were looking at the version on the master branch, which is 1.20.4, and the custom recipe works differently, the one i linked is the 1.20.1 version.

**Comment by Samrel556** [comment]
OOOOOO. Did not catch that. I see the NBT line in the 1.20.1 version. Lemme see

**Comment by Samrel556** [comment]
Ok. Welp. In the future I need to be more careful about the version I am looking at and be better at typing. Many thanks!

**Comment by Flanks255** [comment]
Its all good, 1.20.4 was such a change i had to rewrite how the whole recipe worked.
