### ISSUE TITLE
Pocket Storage seems to reset item durability

### ISSUE THREAD

**Issue by instinxx** [Flanks255/pocketstorage#26]
pocketstorage-1.1.0+1.21-b33

When an item with durability is placed in a Pocket Storage, the items durability gets reset and essentially repairs the item. This has worked successfully on Weapons / Armor and Tools. Any enchantments on the item get removed?

**Comment by Flanks255** [comment]
ya.... i realize how this is happening... ill figure it out lol, i used to block all items with NBT, so nothing enchanted, named, durability, nothing unique, but because of components i cant exactly do that anymore... gotta find a new solution...

**Comment by Flanks255** [comment]
Fixed in 1.1.1, 64d9e4f
