### ISSUE TITLE
How to add items to pocket storage

### ISSUE THREAD

**Issue by Buttersxx** [Flanks255/pocketstorage#27]
It dones they me add items to pocket storage and I can’t find a config file or something to add them in.

**Comment by Flanks255** [comment]
https://github.com/user-attachments/assets/c6b048b8-f540-44a5-a404-c17085843565

**Comment by Buttersxx** [comment]
Okay. I’m trying to add Timeless And Classics ammo inside the pocket storage. I get this message. Only simple items(no data) are allowed inside the pocket storage.

**Comment by Flanks255** [comment]
ah, that means the item has NBT data on it, and cannot be stored in the pocket storage.

**Comment by Buttersxx** [comment]
Okay. Is there any I can do so it can be added?

**Comment by Flanks255** [comment]
Not really, it cannot contain items with NBT data, and thats how the ammo is functioning, you are better off using a bag mod, like one of the many backpack mods, to hold the ammo.

It is possible, in 1.21, depending on how they do the ammo, that it could be held, but i don't know enough about the other mod.
