### ISSUE TITLE
crash on load up[1.16.1] (Caused by: net.minecraftforge.fml.ModLoadingException: Pocket Storage Unit has class loading errors ยง7net/minecraft/util/math/Vec3i)

### ISSUE THREAD

**Issue by SDUBZ** [Flanks255/pocketstorage#3]
Forge :  1.16.1- 32.0.75

PS : pocketstorage-1.15.2-0.7.2

crash report: 
[crash-2020-07-27_11.52.49-client.txt](https://github.com/Flanks255/pocketstorage/files/4979481/crash-2020-07-27_11.52.49-client.txt)

logs:
[latest.log](https://github.com/Flanks255/pocketstorage/files/4979487/latest.log)

**Comment by Flanks255** [comment]
Use the 1.16.1 version, instead of the 1.15 version
