### ISSUE TITLE
1.16.4 Compatability

### ISSUE THREAD

**Issue by GrumpyChunks** [Flanks255/pocketstorage#7]
Is this mod compatible with 1.16.4? It appears to not be available to add to 1.16.4 packs in the various launchers that use CurseForge.

**Comment by Flanks255** [comment]
Flagged for 1.16.4 on CF, just an oversight.
Forge 1.16.4-35.0.5 makes mods that specify they work with 1.16.3 work with 1.16.4, so i never saw the need to upload a new version yet.
