### ISSUE TITLE
Pickup sounds dont play in DW20 1.16.4

### ISSUE THREAD

**Issue by xxbones21xx** [Flanks255/pocketstorage#9]
I noticed that the pickup sound is absent. I personally would like the ability to toggle this sound back on as I use it as a means to ensure I'm picking items up. Thanks.

**Comment by Flanks255** [comment]
Just double checked this morning, the sounds are there, if you aren't hearing them, its likely something is stopping them, or a volume slider is down, etc.

**Comment by xxbones21xx** [comment]
This issue is present in Direwolf20's new 1.16 modpack. I tested another backpack from a mod within this pack that has a auto-pickup option and it too did not make the pickup noise. Not certain what mod would prevent that sound but I may play around. Thanks for investigating.

**Comment by Flanks255** [comment]
Yes it is, i just downloaded the pack and tried it, and it doesnt happen in other packs, going to have to look into this.

**Comment by xxbones21xx** [comment]
I suspect one of the mods listed in his pack alters the behavior, possibly to increase performance. Let me know if I can assist in anyway.
